### ISSUE TITLE
Lack of file data.py

### ISSUE THREAD

**Issue by lincolnBush** [apsdehal/traffic-signs-recognition#1]
Hi:

I have found an issue with the code, In modules/utils.py, this line would produce an error
from data import TrafficSignsDataset

**Comment by RichardMrLu** [comment]
I found the same error..

**Comment by RichardMrLu** [comment]
@apsdehal Hello, thanks for your exclent job, but this data.py is missing, can you updata the file? 
Thanks for your help!

**Comment by apsdehal** [comment]
Oh sorry, I actually missed this issue somehow. Let me find it and update by EOD.

**Comment by apsdehal** [comment]
Done. Apologies, for being late.
